/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentenrollmentmanager;
import static com.mycompany.studentenrollmentmanager.ReadPropertiesFile.Read;
import static com.mycompany.studentenrollmentmanager.ReadPropertiesFile.getPassword;
import static com.mycompany.studentenrollmentmanager.ReadPropertiesFile.getUrl;
import static com.mycompany.studentenrollmentmanager.ReadPropertiesFile.getUsername;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saratotah
 */


public class CourseAdding extends javax.swing.JFrame {
    private Connection con1;
    private PreparedStatement insert;
    private static String url;
    private static String username;
    private static String password;

  
    /**
     * Creates new form CourseAdding
     */
    public CourseAdding() throws Exception {
        initComponents();
        Read();
        
        url = getUrl();
        username = getUsername();
        password = getPassword();
         
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        course_fees_txt = new javax.swing.JTextField();
        course_max_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edit_btn = new javax.swing.JButton();
        course_id_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        course_instructor_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        course_name_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 36)); // NOI18N
        jLabel1.setText("Course Regestration");

        course_fees_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_fees_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("Course Id");

        jLabel3.setText("Instructor");

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Course Name");

        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        course_id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_id_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Max No. of Students");

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        jLabel6.setText("Course Fees");

        course_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_name_txtActionPerformed(evt);
            }
        });

        courses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Instructor", "Max No. of students", "Course Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courses_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courses_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courses_table);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_btn)
                                .addGap(29, 29, 29)
                                .addComponent(delete_btn)
                                .addGap(30, 30, 30)
                                .addComponent(edit_btn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course_fees_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course_max_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course_instructor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(77, 77, 77)
                                    .addComponent(course_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_instructor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_max_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(course_fees_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn)
                            .addComponent(delete_btn)
                            .addComponent(edit_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Read properties (url,username,password and database Name) from config.properties file

    private void table_update(){
        
        int column_num;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            con1 = DriverManager.getConnection(url,username,password);
            insert = con1.prepareStatement("SELECT * FROM courses");         
            ResultSet rs = insert.executeQuery();
            
            ResultSetMetaData Rss = rs.getMetaData();
            column_num = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)courses_table.getModel();
            Df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector(); 
               
                for (int i=1; i <= column_num; i++){
                    v2.add(rs.getInt("course_id"));
                    v2.add(rs.getString("course_name"));
                    v2.add(rs.getString("instructor_name"));
                    v2.add(rs.getInt("max_students"));
                    v2.add(rs.getDouble("course_fee"));

                }
                
                Df.addRow(v2);
            }
        }
        
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(course_enrollment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void course_fees_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_fees_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_fees_txtActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed

        DefaultTableModel Df = (DefaultTableModel)courses_table.getModel();
        int selectedIndex = courses_table.getSelectedRow();
        
        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
            String id_txt = course_id_txt.getText();
            String name_txt = course_name_txt.getText();
            String instructor_txt = course_instructor_txt.getText();
            String max_txt = course_max_txt.getText();
            String fees_txt = course_fees_txt.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            
             con1 = DriverManager.getConnection(url,username,password);
            insert = con1.prepareStatement("UPDATE courses SET course_name=?, instructor_name=?, max_students=?, course_fee=? WHERE course_id=?"); 
            
            insert.setInt(5, id);
            insert.setString(1, name_txt);
            insert.setString(2, instructor_txt);
            insert.setString(3, max_txt);
            insert.setString(4, fees_txt);

            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Course Details Updated");
            table_update();
            
            //empty text fields after registering the student
            
            course_id_txt.setText("");
            course_name_txt.setText("");
            course_instructor_txt.setText("");
            course_max_txt.setText("");
            course_fees_txt.setText("");
            
            course_id_txt.requestFocus();
        }
        
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(course_enrollment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void course_id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_id_txtActionPerformed

    
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String id_txt = course_id_txt.getText();
        String name_txt = course_name_txt.getText();
        String instructor_txt = course_instructor_txt.getText();
        String max_txt = course_max_txt.getText();
        String fees_txt = course_fees_txt.getText();

        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
             con1 = DriverManager.getConnection(url,username,password);
            insert = con1.prepareStatement("INSERT INTO courses(course_id,course_name, instructor_name, max_students, course_fee) VALUES (?,?,?,?,?)"); 
            
            insert.setString(1, id_txt);
            insert.setString(2, name_txt);
            insert.setString(3, instructor_txt);
            insert.setString(4, max_txt);
            insert.setString(5, fees_txt);

            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Course Added");
            table_update();
            //empty text fields after enrolling the student
            
            course_id_txt.setText("");
            course_name_txt.setText("");
            course_instructor_txt.setText("");
            course_max_txt.setText("");
            course_fees_txt.setText("");
            
            course_id_txt.requestFocus();
        }
        
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(course_enrollment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void course_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_name_txtActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
         DefaultTableModel Df = (DefaultTableModel)courses_table.getModel();
        int selectedIndex = courses_table.getSelectedRow();

        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete this course from the system","Warning",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
            
                 con1 = DriverManager.getConnection(url,username,password);
                insert = con1.prepareStatement("DELETE FROM students_enrollment WHERE course_id=?");
                insert = con1.prepareStatement("DELETE FROM courses WHERE course_id=?"); 
                
                insert.setInt(1, id);
                
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this,"Course was deleted from the system");
            table_update();
            //empty text fields after enrolling the student
            
            course_id_txt.setText("");
            course_name_txt.setText("");
            course_instructor_txt.setText("");
            course_max_txt.setText("");
            course_fees_txt.setText("");
            
            course_id_txt.requestFocus();
            
            } 
           
        }
        
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(course_enrollment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void courses_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courses_tableMouseClicked
        DefaultTableModel Df = (DefaultTableModel)courses_table.getModel();
        int selectedIndex = courses_table.getSelectedRow();
        
        course_id_txt.setText(Df.getValueAt(selectedIndex, 0).toString());
        course_name_txt.setText(Df.getValueAt(selectedIndex, 1).toString());    
        course_instructor_txt.setText(Df.getValueAt(selectedIndex, 2).toString());
        course_max_txt.setText(Df.getValueAt(selectedIndex, 3).toString());  
        course_fees_txt.setText(Df.getValueAt(selectedIndex, 4).toString());
    }//GEN-LAST:event_courses_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main().setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseAdding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseAdding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseAdding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseAdding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CourseAdding().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CourseAdding.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField course_fees_txt;
    private javax.swing.JTextField course_id_txt;
    private javax.swing.JTextField course_instructor_txt;
    private javax.swing.JTextField course_max_txt;
    private javax.swing.JTextField course_name_txt;
    private javax.swing.JTable courses_table;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
